apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice-ui
  template:
    metadata:
      labels:
        app: authservice-ui
    spec:
      containers:
      - name: authservice-ui
        image: ghcr.io/mallikarjunaws2025/authservice-ui:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: authservice-ui-service
spec:
  type: NodePort
  selector:
    app: authservice-ui
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
