apiVersion: apps/v1
kind: Deployment
metadata:
  name: authservice-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authservice-api
  template:
    metadata:
      labels:
        app: authservice-api
    spec:
      containers:
      - name: authservice-api
        image: ghcr.io/mallikarjunaws2025/authservice-api:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: authservice-api-service
spec:
  type: NodePort
  selector:
    app: authservice-api
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
